import type { AircraftProfile, AircraftProfileResolutionInput } from './aircraftTypes';

export const aircraftProfiles = {
  generic_trainer: {
    id: 'generic_trainer',
    displayName: 'Generic Test Trainer',
    category: 'prop_trainer',
    meshHintNames: ['trainer', 'generic_trainer', 'test_aircraft'],
    massKg: 900,
    wingAreaM2: 16.2,
    wingspanM: 10.8,
    meanChordM: 1.5,
    referenceLengthM: 7.4,
    inertiaTensorApprox: [1600, 2400, 3100],
    engine: {
      type: 'prop',
      maxThrustN: 3600,
      idleThrustN: 160,
      throttleResponse: 1.6,
    },
    aero: {
      cl0: 0.24,
      clAlpha: 4.9,
      clMax: 1.45,
      cd0: 0.035,
      inducedDragK: 0.055,
      cm0: 0.01,
      cmAlpha: -0.9,
      stallAngleDeg: 15,
      postStallLiftFactor: 0.45,
      sideSlipDrag: 0.12,
    },
    wing: {
      dihedralDeg: 4.5,
      incidenceDeg: 1.5,
      dihedralEffectiveness: 0.095,
      bankStabilityEffectiveness: 0.035,
      surfaceLiftShare: 0.82,
    },
    stabilityDerivatives: {
      longitudinal: {
        cL0: 0.24,
        cLAlpha: 4.9,
        cLQ: 5.6,
        cLElevator: 0.85,
        cD0: 0.035,
        cDAlpha: 0.32,
        cDBeta: 0.12,
        cDControl: 0.035,
        cM0: 0.01,
        cMAlpha: -0.9,
        cMQ: -11,
        cMElevator: 2.4,
      },
      lateralDirectional: {
        cYBeta: -0.62,
        cYP: -0.03,
        cYR: 0.18,
        cYAileron: 0.06,
        cYRudder: 0.7,
        cRollBeta: 0.028,
        cRollP: -0.62,
        cRollR: 0.1,
        cRollAileron: 0.2,
        cRollRudder: 0.05,
        cNBeta: 0.105,
        cNP: -0.03,
        cNR: -0.28,
        cNAileron: -0.03,
        cNRudder: 0.22,
      },
    },
    controlSurfaces: {
      elevatorMaxDeg: 18,
      aileronMaxDeg: 13,
      rudderMaxDeg: 20,
      elevatorRateDegPerSec: 90,
      aileronRateDegPerSec: 105,
      rudderRateDegPerSec: 85,
    },
    liftingSurfaces: {
      horizontalTailAreaM2: 3.4,
      verticalTailAreaM2: 1.8,
      tailArmM: 4.1,
    },
    control: {
      elevatorPower: 5200,
      aileronPower: 7800,
      rudderPower: 2800,
      pitchDamping: 2300,
      rollDamping: 2600,
      yawDamping: 1700,
      minControlDynamicPressurePa: 850,
    },
    pilotControl: {
      mousePitchSensitivity: 0.002,
      mouseRollSensitivity: 0.0051,
      keyboardPitchRate: 2.4,
      keyboardRollRate: 4.2,
      keyboardYawRate: 2.6,
      inputSmoothing: 9,
      pitchCenteringRate: 0.12,
      rollCenteringRate: 0.16,
      yawCenteringRate: 2.8,
      axisDeadzone: 0.008,
      pitchCurve: 1.18,
      rollCurve: 0.78,
      yawCurve: 1,
      rollDeadzone: 0.002,
      yawDeadzone: 0.02,
      yokeReturnDelaySeconds: 0.18,
      yokeReturnRampSeconds: 0.55,
      mouseActivityThreshold: 0.35,
    },
    limits: {
      maxSpeedMps: 95,
      neverExceedSpeedMps: 118,
      maxLoadFactor: 5.5,
      minThrottle: 0,
      maxThrottle: 1,
      minAeroSpeedMps: 18,
    },
    spawn: {
      position: [0, 260, 0],
      rotationEulerDeg: [0, 0, 0],
      initialSpeedMps: 42,
      altitudeM: 260,
    },
    visual: {
      modelScale: [1, 1, 1],
      modelRotationEulerDeg: [0, 0, 0],
      chaseCameraDistance: 18,
      chaseCameraHeight: 5,
    },
    tuningNotes: [
      'Forgiving first playable profile with strong damping and broad stall recovery.',
      'Not intended to represent a real aircraft.',
    ],
  },
  ww2_fighter_baseline: {
    id: 'ww2_fighter_baseline',
    displayName: 'WW2 Fighter Baseline',
    category: 'ww2_fighter',
    meshHintNames: ['ww2_fighter', 'warbird', 'fighter_baseline'],
    massKg: 3000,
    wingAreaM2: 22.5,
    wingspanM: 11.4,
    meanChordM: 1.95,
    referenceLengthM: 9.1,
    inertiaTensorApprox: [5200, 8200, 10200],
    engine: {
      type: 'prop',
      maxThrustN: 11500,
      idleThrustN: 500,
      throttleResponse: 1.2,
    },
    aero: {
      cl0: 0.2,
      clAlpha: 5.3,
      clMax: 1.6,
      cd0: 0.03,
      inducedDragK: 0.048,
      cm0: 0.005,
      cmAlpha: -1.05,
      stallAngleDeg: 16,
      postStallLiftFactor: 0.38,
      sideSlipDrag: 0.16,
    },
    wing: {
      dihedralDeg: 2.5,
      incidenceDeg: 1,
      dihedralEffectiveness: 0.055,
      bankStabilityEffectiveness: 0.018,
      surfaceLiftShare: 0.84,
    },
    stabilityDerivatives: {
      longitudinal: {
        cL0: 0.2,
        cLAlpha: 5.3,
        cLQ: 4.8,
        cLElevator: 0.95,
        cD0: 0.03,
        cDAlpha: 0.28,
        cDBeta: 0.16,
        cDControl: 0.04,
        cM0: 0.005,
        cMAlpha: -1.05,
        cMQ: -8.8,
        cMElevator: 2.8,
      },
      lateralDirectional: {
        cYBeta: -0.55,
        cYP: -0.04,
        cYR: 0.2,
        cYAileron: 0.07,
        cYRudder: 0.75,
        cRollBeta: 0.02,
        cRollP: -0.68,
        cRollR: 0.12,
        cRollAileron: 0.28,
        cRollRudder: 0.055,
        cNBeta: 0.095,
        cNP: -0.025,
        cNR: -0.25,
        cNAileron: -0.045,
        cNRudder: 0.29,
      },
    },
    controlSurfaces: {
      elevatorMaxDeg: 17,
      aileronMaxDeg: 15,
      rudderMaxDeg: 20,
      elevatorRateDegPerSec: 130,
      aileronRateDegPerSec: 140,
      rudderRateDegPerSec: 110,
    },
    liftingSurfaces: {
      horizontalTailAreaM2: 4.5,
      verticalTailAreaM2: 2.2,
      tailArmM: 5,
    },
    control: {
      elevatorPower: 18500,
      aileronPower: 32000,
      rudderPower: 9000,
      pitchDamping: 8200,
      rollDamping: 10600,
      yawDamping: 6500,
      minControlDynamicPressurePa: 1100,
    },
    pilotControl: {
      mousePitchSensitivity: 0.0022,
      mouseRollSensitivity: 0.0072,
      keyboardPitchRate: 3.1,
      keyboardRollRate: 4.2,
      keyboardYawRate: 3,
      inputSmoothing: 10,
      pitchCenteringRate: 0.1,
      rollCenteringRate: 0.11,
      yawCenteringRate: 3.2,
      axisDeadzone: 0.012,
      pitchCurve: 1.12,
      rollCurve: 0.7,
      yawCurve: 1,
      rollDeadzone: 0.002,
      yawDeadzone: 0.018,
      yokeReturnDelaySeconds: 0.16,
      yokeReturnRampSeconds: 0.48,
      mouseActivityThreshold: 0.35,
    },
    limits: {
      maxSpeedMps: 165,
      neverExceedSpeedMps: 205,
      maxLoadFactor: 8,
      minThrottle: 0,
      maxThrottle: 1,
      minAeroSpeedMps: 28,
    },
    spawn: {
      position: [0, 420, 0],
      rotationEulerDeg: [0, 0, 0],
      initialSpeedMps: 82,
      altitudeM: 420,
    },
    visual: {
      modelScale: [1, 1, 1],
      modelRotationEulerDeg: [0, 0, 0],
      chaseCameraDistance: 22,
      chaseCameraHeight: 6,
    },
    tuningNotes: ['Agile fighter-like baseline. Use as a parent idea for named warbirds.'],
  },
  spitfire_like: {
    id: 'spitfire_like',
    displayName: 'Spitfire-Like Fighter',
    category: 'ww2_fighter',
    meshHintNames: ['spitfire', 'ww2_spitfire', 'spitfire_mk_i', 'meshy_spitfire_001'],
    massKg: 2950,
    wingAreaM2: 22.4,
    wingspanM: 11.2,
    meanChordM: 2.0,
    referenceLengthM: 9.1,
    inertiaTensorApprox: [5000, 7900, 9800],
    engine: {
      type: 'prop',
      maxThrustN: 12200,
      idleThrustN: 520,
      throttleResponse: 1.25,
    },
    aero: {
      cl0: 0.22,
      clAlpha: 5.5,
      clMax: 1.7,
      cd0: 0.031,
      inducedDragK: 0.046,
      cm0: 0.0,
      cmAlpha: -1.1,
      stallAngleDeg: 16.5,
      postStallLiftFactor: 0.42,
      sideSlipDrag: 0.15,
    },
    wing: {
      dihedralDeg: 5,
      incidenceDeg: 1,
      dihedralEffectiveness: 0.075,
      bankStabilityEffectiveness: 0.025,
      surfaceLiftShare: 0.86,
    },
    stabilityDerivatives: {
      longitudinal: {
        cL0: 0.22,
        cLAlpha: 5.5,
        cLQ: 4.7,
        cLElevator: 0.98,
        cD0: 0.031,
        cDAlpha: 0.27,
        cDBeta: 0.15,
        cDControl: 0.038,
        cM0: 0,
        cMAlpha: -1.1,
        cMQ: -8.5,
        cMElevator: 2.9,
      },
      lateralDirectional: {
        cYBeta: -0.56,
        cYP: -0.04,
        cYR: 0.2,
        cYAileron: 0.07,
        cYRudder: 0.78,
        cRollBeta: 0.028,
        cRollP: -0.66,
        cRollR: 0.11,
        cRollAileron: 0.3,
        cRollRudder: 0.055,
        cNBeta: 0.105,
        cNP: -0.024,
        cNR: -0.26,
        cNAileron: -0.042,
        cNRudder: 0.3,
      },
    },
    controlSurfaces: {
      elevatorMaxDeg: 17,
      aileronMaxDeg: 15,
      rudderMaxDeg: 21,
      elevatorRateDegPerSec: 130,
      aileronRateDegPerSec: 135,
      rudderRateDegPerSec: 110,
    },
    liftingSurfaces: {
      horizontalTailAreaM2: 4.3,
      verticalTailAreaM2: 2.1,
      tailArmM: 5,
    },
    control: {
      elevatorPower: 19500,
      aileronPower: 34000,
      rudderPower: 9200,
      pitchDamping: 8400,
      rollDamping: 10200,
      yawDamping: 6400,
      minControlDynamicPressurePa: 1100,
    },
    pilotControl: {
      mousePitchSensitivity: 0.0022,
      mouseRollSensitivity: 0.0076,
      keyboardPitchRate: 3.2,
      keyboardRollRate: 4.4,
      keyboardYawRate: 3,
      inputSmoothing: 10,
      pitchCenteringRate: 0.1,
      rollCenteringRate: 0.1,
      yawCenteringRate: 3.2,
      axisDeadzone: 0.012,
      pitchCurve: 1.1,
      rollCurve: 0.68,
      yawCurve: 1,
      rollDeadzone: 0.002,
      yawDeadzone: 0.018,
      yokeReturnDelaySeconds: 0.16,
      yokeReturnRampSeconds: 0.45,
      mouseActivityThreshold: 0.35,
    },
    limits: {
      maxSpeedMps: 172,
      neverExceedSpeedMps: 214,
      maxLoadFactor: 8.5,
      minThrottle: 0,
      maxThrottle: 1,
      minAeroSpeedMps: 30,
    },
    spawn: {
      position: [0, 430, 0],
      rotationEulerDeg: [0, 0, 0],
      initialSpeedMps: 88,
      altitudeM: 430,
    },
    visual: {
      modelScale: [1, 1, 1],
      modelRotationEulerDeg: [0, 0, 0],
      chaseCameraDistance: 22,
      chaseCameraHeight: 6,
    },
    tuningNotes: [
      'Game-friendly profile inspired by Spitfire-class aircraft.',
      'Not historically authoritative; tune for feel before accuracy.',
    ],
  },
  heavy_bomber_baseline: {
    id: 'heavy_bomber_baseline',
    displayName: 'Heavy Bomber Baseline',
    category: 'heavy_bomber',
    meshHintNames: ['bomber', 'heavy_bomber', 'four_engine_bomber'],
    massKg: 24500,
    wingAreaM2: 120,
    wingspanM: 31,
    meanChordM: 3.9,
    referenceLengthM: 22,
    inertiaTensorApprox: [95000, 180000, 230000],
    engine: {
      type: 'prop',
      maxThrustN: 52000,
      idleThrustN: 2600,
      throttleResponse: 0.75,
    },
    aero: {
      cl0: 0.32,
      clAlpha: 4.7,
      clMax: 1.55,
      cd0: 0.045,
      inducedDragK: 0.07,
      cm0: 0.015,
      cmAlpha: -0.8,
      stallAngleDeg: 14,
      postStallLiftFactor: 0.34,
      sideSlipDrag: 0.24,
    },
    wing: {
      dihedralDeg: 6,
      incidenceDeg: 2,
      dihedralEffectiveness: 0.11,
      bankStabilityEffectiveness: 0.042,
      surfaceLiftShare: 0.88,
    },
    stabilityDerivatives: {
      longitudinal: {
        cL0: 0.32,
        cLAlpha: 4.7,
        cLQ: 7.8,
        cLElevator: 0.7,
        cD0: 0.045,
        cDAlpha: 0.42,
        cDBeta: 0.24,
        cDControl: 0.05,
        cM0: 0.015,
        cMAlpha: -0.8,
        cMQ: -15,
        cMElevator: 2,
      },
      lateralDirectional: {
        cYBeta: -0.88,
        cYP: -0.05,
        cYR: 0.26,
        cYAileron: 0.04,
        cYRudder: 0.55,
        cRollBeta: 0.045,
        cRollP: -0.82,
        cRollR: 0.08,
        cRollAileron: 0.16,
        cRollRudder: 0.06,
        cNBeta: 0.18,
        cNP: -0.045,
        cNR: -0.42,
        cNAileron: -0.02,
        cNRudder: 0.19,
      },
    },
    controlSurfaces: {
      elevatorMaxDeg: 14,
      aileronMaxDeg: 10,
      rudderMaxDeg: 18,
      elevatorRateDegPerSec: 55,
      aileronRateDegPerSec: 45,
      rudderRateDegPerSec: 50,
    },
    liftingSurfaces: {
      horizontalTailAreaM2: 24,
      verticalTailAreaM2: 16,
      tailArmM: 13.5,
    },
    control: {
      elevatorPower: 95000,
      aileronPower: 125000,
      rudderPower: 74000,
      pitchDamping: 76000,
      rollDamping: 98000,
      yawDamping: 68000,
      minControlDynamicPressurePa: 950,
    },
    pilotControl: {
      mousePitchSensitivity: 0.0014,
      mouseRollSensitivity: 0.0032,
      keyboardPitchRate: 1.6,
      keyboardRollRate: 2,
      keyboardYawRate: 1.8,
      inputSmoothing: 6.5,
      pitchCenteringRate: 0.16,
      rollCenteringRate: 0.14,
      yawCenteringRate: 2.2,
      axisDeadzone: 0.018,
      pitchCurve: 1.35,
      rollCurve: 0.9,
      yawCurve: 1.1,
      rollDeadzone: 0.004,
      yawDeadzone: 0.025,
      yokeReturnDelaySeconds: 0.22,
      yokeReturnRampSeconds: 0.8,
      mouseActivityThreshold: 0.35,
    },
    limits: {
      maxSpeedMps: 128,
      neverExceedSpeedMps: 158,
      maxLoadFactor: 3.5,
      minThrottle: 0,
      maxThrottle: 1,
      minAeroSpeedMps: 35,
    },
    spawn: {
      position: [0, 620, 0],
      rotationEulerDeg: [0, 0, 0],
      initialSpeedMps: 75,
      altitudeM: 620,
    },
    visual: {
      modelScale: [1.7, 1.7, 1.7],
      modelRotationEulerDeg: [0, 0, 0],
      chaseCameraDistance: 42,
      chaseCameraHeight: 12,
    },
    tuningNotes: ['Slow, heavy, damped baseline for large aircraft silhouettes.'],
  },
} satisfies Record<string, AircraftProfile>;

export type AircraftProfileId = keyof typeof aircraftProfiles;

export const defaultAircraftProfileId: AircraftProfileId = 'generic_trainer';

export function getAircraftProfile(profileId: string = defaultAircraftProfileId): AircraftProfile {
  return aircraftProfiles[profileId as AircraftProfileId] ?? aircraftProfiles[defaultAircraftProfileId];
}

export function resolveAircraftProfile(input: AircraftProfileResolutionInput): AircraftProfile {
  if (input.aircraftProfileId && aircraftProfiles[input.aircraftProfileId as AircraftProfileId]) {
    return aircraftProfiles[input.aircraftProfileId as AircraftProfileId];
  }

  const candidates = [input.assetId, input.displayName, input.meshHintName]
    .filter((value): value is string => Boolean(value))
    .map((value) => value.toLowerCase().replaceAll(/[\s-]+/g, '_'));

  for (const profile of Object.values(aircraftProfiles)) {
    const hints = [profile.id, profile.displayName, ...(profile.meshHintNames ?? [])].map((value) =>
      value.toLowerCase().replaceAll(/[\s-]+/g, '_'),
    );
    if (candidates.some((candidate) => hints.includes(candidate))) {
      return profile;
    }
  }

  return aircraftProfiles[defaultAircraftProfileId];
}
